version: '3.7'
services:
  db:
    image: postgres:13.4
<<<<<<< HEAD
    networks:
      - whereze
    env_file: .env
    ports:
      - 5432:5432
=======
    ports: 
      - 5432:5432
    networks:
      - whereze
    env_file: .env
>>>>>>> 12b73a389750f15ab18983fc549d484dbf263ce0

networks:
  whereze: