version: '3.7'
services:
  db:
    image: postgres:13.4
    networks:
      - whereze
    env_file: .env
    ports:
      - 5432:5432

  app:
    build: .
    networks:
      - whereze
    env_file: .env
    ports:
      - 5000:5000

networks:
  whereze:
